[build]
  command = "npm install --legacy-peer-deps && NODE_OPTIONS='--max-old-space-size=4096' npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096"

[functions]
  node_bundler = "zisi"
  external_node_modules = ["@remix-run/node"]
  included_files = ["build/**"]


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
