[build]
  publish = "build/client"
  # Force fresh install - Linux compatible commands
  command = "rm -f pnpm-lock.yaml && rm -rf node_modules && npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NETLIFY_USE_PNPM = "false"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "netlify/functions"
  included_files = ["build/**"]
  node_bundler = "esbuild"
  external_node_modules = ["react", "react-dom"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
